"""initial

Revision ID: f268c2295e68
Revises:
Create Date: 2026-04-23 04:00:09.355958

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f268c2295e68"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "open_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("prefix", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("tail", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("key_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("allowed_agent_ids", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=True),
        sa.Column("quota_total", sa.Integer(), nullable=True),
        sa.Column("quota_used", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_open_keys_admin_user_id"), "open_keys", ["admin_user_id"], unique=False)
    op.create_index(op.f("ix_open_keys_key_hash"), "open_keys", ["key_hash"], unique=True)
    op.add_column("api_tokens", sa.Column("expires_at", sa.DateTime(), nullable=True))
    op.add_column("call_logs", sa.Column("open_key_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_call_logs_open_key_id"), "call_logs", ["open_key_id"], unique=False)
    op.create_foreign_key(None, "call_logs", "open_keys", ["open_key_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "call_logs", type_="foreignkey")
    op.drop_index(op.f("ix_call_logs_open_key_id"), table_name="call_logs")
    op.drop_column("call_logs", "open_key_id")
    op.drop_column("api_tokens", "expires_at")
    op.drop_index(op.f("ix_open_keys_key_hash"), table_name="open_keys")
    op.drop_index(op.f("ix_open_keys_admin_user_id"), table_name="open_keys")
    op.drop_table("open_keys")
    # ### end Alembic commands ###
