/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as R404IndexRouteImport } from './routes/404/index'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthRoutesIndexRouteImport } from './routes/_auth/routes/index'
import { Route as AuthPromptsIndexRouteImport } from './routes/_auth/prompts/index'
import { Route as AuthOpenKeysIndexRouteImport } from './routes/_auth/open-keys/index'
import { Route as AuthMcpServersIndexRouteImport } from './routes/_auth/mcp-servers/index'
import { Route as AuthLogsIndexRouteImport } from './routes/_auth/logs/index'
import { Route as AuthKeysIndexRouteImport } from './routes/_auth/keys/index'
import { Route as AuthGatewaysIndexRouteImport } from './routes/_auth/gateways/index'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthApiTokensIndexRouteImport } from './routes/_auth/api-tokens/index'
import { Route as AuthAlertsIndexRouteImport } from './routes/_auth/alerts/index'
import { Route as AuthAgentsIndexRouteImport } from './routes/_auth/agents/index'
import { Route as Auth403IndexRouteImport } from './routes/_auth/403/index'
import { Route as AuthChatAgentIdRouteImport } from './routes/_auth/chat/$agentId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404IndexRoute = R404IndexRouteImport.update({
  id: '/404/',
  path: '/404/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRoutesIndexRoute = AuthRoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPromptsIndexRoute = AuthPromptsIndexRouteImport.update({
  id: '/prompts/',
  path: '/prompts/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOpenKeysIndexRoute = AuthOpenKeysIndexRouteImport.update({
  id: '/open-keys/',
  path: '/open-keys/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMcpServersIndexRoute = AuthMcpServersIndexRouteImport.update({
  id: '/mcp-servers/',
  path: '/mcp-servers/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLogsIndexRoute = AuthLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthKeysIndexRoute = AuthKeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthGatewaysIndexRoute = AuthGatewaysIndexRouteImport.update({
  id: '/gateways/',
  path: '/gateways/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthApiTokensIndexRoute = AuthApiTokensIndexRouteImport.update({
  id: '/api-tokens/',
  path: '/api-tokens/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAlertsIndexRoute = AuthAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAgentsIndexRoute = AuthAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const Auth403IndexRoute = Auth403IndexRouteImport.update({
  id: '/403/',
  path: '/403/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthChatAgentIdRoute = AuthChatAgentIdRouteImport.update({
  id: '/chat/$agentId',
  path: '/chat/$agentId',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404/': typeof R404IndexRoute
  '/login/': typeof LoginIndexRoute
  '/chat/$agentId': typeof AuthChatAgentIdRoute
  '/403/': typeof Auth403IndexRoute
  '/agents/': typeof AuthAgentsIndexRoute
  '/alerts/': typeof AuthAlertsIndexRoute
  '/api-tokens/': typeof AuthApiTokensIndexRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/gateways/': typeof AuthGatewaysIndexRoute
  '/keys/': typeof AuthKeysIndexRoute
  '/logs/': typeof AuthLogsIndexRoute
  '/mcp-servers/': typeof AuthMcpServersIndexRoute
  '/open-keys/': typeof AuthOpenKeysIndexRoute
  '/prompts/': typeof AuthPromptsIndexRoute
  '/routes/': typeof AuthRoutesIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/users/': typeof AuthUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404IndexRoute
  '/login': typeof LoginIndexRoute
  '/chat/$agentId': typeof AuthChatAgentIdRoute
  '/403': typeof Auth403IndexRoute
  '/agents': typeof AuthAgentsIndexRoute
  '/alerts': typeof AuthAlertsIndexRoute
  '/api-tokens': typeof AuthApiTokensIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/gateways': typeof AuthGatewaysIndexRoute
  '/keys': typeof AuthKeysIndexRoute
  '/logs': typeof AuthLogsIndexRoute
  '/mcp-servers': typeof AuthMcpServersIndexRoute
  '/open-keys': typeof AuthOpenKeysIndexRoute
  '/prompts': typeof AuthPromptsIndexRoute
  '/routes': typeof AuthRoutesIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/users': typeof AuthUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/404/': typeof R404IndexRoute
  '/login/': typeof LoginIndexRoute
  '/_auth/chat/$agentId': typeof AuthChatAgentIdRoute
  '/_auth/403/': typeof Auth403IndexRoute
  '/_auth/agents/': typeof AuthAgentsIndexRoute
  '/_auth/alerts/': typeof AuthAlertsIndexRoute
  '/_auth/api-tokens/': typeof AuthApiTokensIndexRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/gateways/': typeof AuthGatewaysIndexRoute
  '/_auth/keys/': typeof AuthKeysIndexRoute
  '/_auth/logs/': typeof AuthLogsIndexRoute
  '/_auth/mcp-servers/': typeof AuthMcpServersIndexRoute
  '/_auth/open-keys/': typeof AuthOpenKeysIndexRoute
  '/_auth/prompts/': typeof AuthPromptsIndexRoute
  '/_auth/routes/': typeof AuthRoutesIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404/'
    | '/login/'
    | '/chat/$agentId'
    | '/403/'
    | '/agents/'
    | '/alerts/'
    | '/api-tokens/'
    | '/dashboard/'
    | '/gateways/'
    | '/keys/'
    | '/logs/'
    | '/mcp-servers/'
    | '/open-keys/'
    | '/prompts/'
    | '/routes/'
    | '/settings/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/login'
    | '/chat/$agentId'
    | '/403'
    | '/agents'
    | '/alerts'
    | '/api-tokens'
    | '/dashboard'
    | '/gateways'
    | '/keys'
    | '/logs'
    | '/mcp-servers'
    | '/open-keys'
    | '/prompts'
    | '/routes'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/404/'
    | '/login/'
    | '/_auth/chat/$agentId'
    | '/_auth/403/'
    | '/_auth/agents/'
    | '/_auth/alerts/'
    | '/_auth/api-tokens/'
    | '/_auth/dashboard/'
    | '/_auth/gateways/'
    | '/_auth/keys/'
    | '/_auth/logs/'
    | '/_auth/mcp-servers/'
    | '/_auth/open-keys/'
    | '/_auth/prompts/'
    | '/_auth/routes/'
    | '/_auth/settings/'
    | '/_auth/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  R404IndexRoute: typeof R404IndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404/': {
      id: '/404/'
      path: '/404'
      fullPath: '/404/'
      preLoaderRoute: typeof R404IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/routes/': {
      id: '/_auth/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof AuthRoutesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/prompts/': {
      id: '/_auth/prompts/'
      path: '/prompts'
      fullPath: '/prompts/'
      preLoaderRoute: typeof AuthPromptsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/open-keys/': {
      id: '/_auth/open-keys/'
      path: '/open-keys'
      fullPath: '/open-keys/'
      preLoaderRoute: typeof AuthOpenKeysIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/mcp-servers/': {
      id: '/_auth/mcp-servers/'
      path: '/mcp-servers'
      fullPath: '/mcp-servers/'
      preLoaderRoute: typeof AuthMcpServersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/logs/': {
      id: '/_auth/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AuthLogsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/keys/': {
      id: '/_auth/keys/'
      path: '/keys'
      fullPath: '/keys/'
      preLoaderRoute: typeof AuthKeysIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/gateways/': {
      id: '/_auth/gateways/'
      path: '/gateways'
      fullPath: '/gateways/'
      preLoaderRoute: typeof AuthGatewaysIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/api-tokens/': {
      id: '/_auth/api-tokens/'
      path: '/api-tokens'
      fullPath: '/api-tokens/'
      preLoaderRoute: typeof AuthApiTokensIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/alerts/': {
      id: '/_auth/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AuthAlertsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/agents/': {
      id: '/_auth/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthAgentsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/403/': {
      id: '/_auth/403/'
      path: '/403'
      fullPath: '/403/'
      preLoaderRoute: typeof Auth403IndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/chat/$agentId': {
      id: '/_auth/chat/$agentId'
      path: '/chat/$agentId'
      fullPath: '/chat/$agentId'
      preLoaderRoute: typeof AuthChatAgentIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthChatAgentIdRoute: typeof AuthChatAgentIdRoute
  Auth403IndexRoute: typeof Auth403IndexRoute
  AuthAgentsIndexRoute: typeof AuthAgentsIndexRoute
  AuthAlertsIndexRoute: typeof AuthAlertsIndexRoute
  AuthApiTokensIndexRoute: typeof AuthApiTokensIndexRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthGatewaysIndexRoute: typeof AuthGatewaysIndexRoute
  AuthKeysIndexRoute: typeof AuthKeysIndexRoute
  AuthLogsIndexRoute: typeof AuthLogsIndexRoute
  AuthMcpServersIndexRoute: typeof AuthMcpServersIndexRoute
  AuthOpenKeysIndexRoute: typeof AuthOpenKeysIndexRoute
  AuthPromptsIndexRoute: typeof AuthPromptsIndexRoute
  AuthRoutesIndexRoute: typeof AuthRoutesIndexRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthChatAgentIdRoute: AuthChatAgentIdRoute,
  Auth403IndexRoute: Auth403IndexRoute,
  AuthAgentsIndexRoute: AuthAgentsIndexRoute,
  AuthAlertsIndexRoute: AuthAlertsIndexRoute,
  AuthApiTokensIndexRoute: AuthApiTokensIndexRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthGatewaysIndexRoute: AuthGatewaysIndexRoute,
  AuthKeysIndexRoute: AuthKeysIndexRoute,
  AuthLogsIndexRoute: AuthLogsIndexRoute,
  AuthMcpServersIndexRoute: AuthMcpServersIndexRoute,
  AuthOpenKeysIndexRoute: AuthOpenKeysIndexRoute,
  AuthPromptsIndexRoute: AuthPromptsIndexRoute,
  AuthRoutesIndexRoute: AuthRoutesIndexRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  R404IndexRoute: R404IndexRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
